### ISSUE TITLE
MIssing commas in `__init__.py`

### ISSUE THREAD

**Issue by dmopalmer** [parsotat/BatAnalysis#11]
On the main branch, in `__init__.py`, you need commas to delimit the members of `__all__`.  Otherwise it just concatenates them all together

```
__all__ = [
    'batobservation'
    'bat_survey'
    'bat_tte'
    'batlib'
    'plotting'
    'mosaic'
]
```

Error message:
```
----> 1 from batanalysis import *

AttributeError: module 'batanalysis' has no attribute 'batobservationbat_surveybat_ttebatlibplottingmosaic'
```

**Comment by parsotat** [comment]
you can temporarily work around this by doing `import batanalysis as ba` while I incorporate a pull request

**Comment by parsotat** [comment]
v1.0.6 has been uploaded to PyPI and fixes this issue. Can you verify @dmopalmer?
